{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: ph-ee-connector-ams-mifos-c-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
#- apiGroups: [ "" ]
#  resources: [ "pods","pods/attach","pods/exec","pods/port-forward","pods/proxy","services/proxy" ]
#  verbs: ["get", "watch", "list"]
{{- end -}}