apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ph-ee-operator-c-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: payment-hub
    namespace: {{ .Release.Namespace }}