apiVersion: v2
description: PaymentHub EE Barebone Edition
type: application
name: ph-ee-g2psandbox
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine-0.0.1-SNAPSHOT
  version: 0.0.1-SNAPSHOT
