{{- if .Values.kibana.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ph-ee-operator-c-role-binding
subjects:
  - kind: ServiceAccount
    name: payment-hub # name of your service account
    namespace: paymenthub # this is the namespace your service account is in
  - kind: User
    name: default # "name" is case sensitive
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: ph-ee-operator-c-role
  apiGroup: rbac.authorization.k8s.io

  {{- end -}}