#delete this file based on point delete parent chart role manifest


  {{- if .Values.kibana.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ph-ee-operator-c-role
  namespace: paymenthub
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get"]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: ["get", "list"]
  {{- end -}}