kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: ph-ee-operator-c-role
rules:
  - apiGroups: [ "" ]
  resources:
    - bindings
    - componentstatuses
    - configmaps
    - endpoints
    - events
    - limitranges
    - namespaces
    - namespaces/finalize
    - namespaces/status
    - nodes
    - nodes/proxy
    - nodes/status
    - persistentvolumeclaims
    - persistentvolumeclaims/status
    - persistentvolumes
    - persistentvolumes/status
    - pods
    - pods/attach
    - pods/binding
    - pods/eviction
    #      - pods/exec
    - pods/log
    - pods/proxy
    - pods/status
    - podtemplates
    - replicationcontrollers
    - replicationcontrollers/scale
    - replicationcontrollers/status
    - resourcequotas
    - resourcequotas/status
    - serviceaccounts
    - services
    - services/proxy
    - services/status
    verbs:
      - get
      - list
      - watch