#delete this file based on point delete parent chart role manifest


{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payment-hub-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs: ["get", "create", "update"]
  {{- end -}}