apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ph-ee-operator-c-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: [""]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: ["get", "list"]
