kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: ph-ee-operator-c-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
      - networking.k8s.io
    resources:
      - componentstatuses
      - cronjobs
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - pods/log
      - persistentvolumes
      - persistentvolumeclaims
      - poddisruptionbudgets
      - roles
      - rolebindings
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - secrets
      - statefulsets