#delete this file based on point delete parent chart role manifest


  {{- if .Values.kibana.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payment-hub-role
  namespace: paymenthub
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs: ["get", "create", "update"]
  {{- end -}}