kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: ph-ee-operator-c-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods","pods/attach","pods/exec","pods/port-forward","pods/proxy","services/proxy" ]
    verbs: [""]